apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: tejasdesai0531/sf-restaurant
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://seven-food:sevenfood.com@seven-food.717os.mongodb.net/restaurant?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-srv
spec:
  selector:
    app: restaurant
  ports:
    - name: restaurant
      protocol: TCP
      port: 3000
      targetPort: 3000